"""
GUIDED ADVISOR — Dynamic Cross-Questioning + Researched Recommendations
=======================================================================
Handles: "suggest smartphones under 20k", "best laptop for coding",
         "recommend headphones", "which phone should I buy", etc.

Flow:
  1. Detects recommendation intent
  2. Extracts known constraints (budget, brand) from the original sentence
  3. Generates the MOST RELEVANT next question using LLM (skips what's known)
  4. Asks 2-3 questions MAX, one at a time
  5. Runs DuckDuckGo research with collected preferences
  6. Returns top 3 with specs + Flipkart/Amazon India buy links
  7. Speaks a concise summary, full report available in text

Place this file at: agent/advisor.py
"""

import asyncio
import json
import logging
import re
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class RecommendationSession:
    session_id: str
    original_query: str
    category: str
    known_constraints: Dict       # from initial query (budget, brand, etc.)
    answers: Dict[str, str]       # question → answer pairs
    questions_asked: List[str]
    created_at: float = field(default_factory=time.time)
    completed: bool = False
    result_text: Optional[str] = None
    result_spoken: Optional[str] = None


class GuidedAdvisor:
    """
    Multi-turn recommendation engine with dynamic questioning.

    State machine:
      IDLE → NEW_SESSION (extract constraints, ask Q1)
           → ANSWERING   (user answers Q1 → ask Q2 or research)
           → RESEARCHING → DONE

    The key insight: questions are generated by LLM based on what's MISSING,
    not from a fixed list. So if user said "under 20k", we never ask budget.
    """

    CATEGORY_MAP = {
        "smartphone": ["smartphone", "phone", "mobile", "android", "iphone"],
        "laptop":     ["laptop", "notebook", "macbook", "chromebook"],
        "headphone":  ["headphone", "earphone", "earbud", "earbuds", "headset", "earphones"],
        "tablet":     ["tablet", "ipad"],
        "tv":         ["tv", "television", "smart tv"],
        "camera":     ["camera", "dslr", "mirrorless"],
        "smartwatch": ["watch", "smartwatch", "wearable", "fitbit"],
        "speaker":    ["speaker", "bluetooth speaker", "soundbar"],
        "keyboard":   ["keyboard", "mechanical keyboard"],
        "monitor":    ["monitor", "display", "screen"],
        "charger":    ["charger", "power bank", "powerbank"],
    }

    # Candidate questions per category (LLM picks the best ones dynamically)
    QUESTION_POOL = {
        "smartphone": [
            "What will you mainly use it for — gaming, photography, or everyday tasks?",
            "Any brand preference, or open to all options?",
            "Battery life or performance — which matters more to you?",
            "Do you prefer a compact phone under 6 inches, or a larger screen?",
            "Stock Android or are you okay with custom UI like MIUI or One UI?",
        ],
        "laptop": [
            "What's your primary use — coding, gaming, design, or everyday work?",
            "Windows or open to macOS too?",
            "Do you carry it daily, or mostly use it at a desk?",
            "Do you need a dedicated GPU for gaming or creative work?",
            "Preferred screen size — 13, 14, 15, or 16 inches?",
        ],
        "headphone": [
            "Over-ear, on-ear, or in-ear earbuds?",
            "Do you need active noise cancellation?",
            "Mainly for music, calls, gaming, or all three?",
            "Wired or wireless preferred?",
        ],
        "tv": [
            "What screen size are you looking for?",
            "Mainly for streaming, cable TV, or gaming?",
            "4K or Full HD is fine?",
        ],
        "_default": [
            "What will you mainly use it for?",
            "Any brand preferences?",
            "Any specific must-have features?",
        ]
    }

    # Trigger phrases that indicate a recommendation query
    TRIGGERS = [
        "suggest", "recommend", "which is best", "best ", "good ",
        "should i buy", "worth buying", "top 3", "top three",
        "which phone", "which laptop", "which headphone", "which tablet",
        "what phone", "what laptop", "compare", "vs ", "versus",
        "good phones", "good laptops", "worth it",
    ]

    def __init__(self, groq_api_key: str):
        self._api_key = groq_api_key
        self._client = None
        self._sessions: Dict[str, RecommendationSession] = {}
        self._active_id: Optional[str] = None

    def _groq(self):
        if not self._client:
            from groq import Groq
            self._client = Groq(api_key=self._api_key)
        return self._client

    # ── PUBLIC ─────────────────────────────────────────────────────────────

    def is_recommendation_query(self, text: str) -> bool:
        t = text.lower()
        return any(tr in t for tr in self.TRIGGERS)

    def has_active_session(self) -> bool:
        if not self._active_id:
            return False
        s = self._sessions.get(self._active_id)
        return s is not None and not s.completed

    async def start_or_continue(
        self,
        user_text: str,
        speak_fn: Callable[[str], None]
    ) -> Optional[str]:
        """
        Call for any recommendation query or follow-up answer.
        Returns final recommendation string when done, None while still questioning.
        speak_fn is called immediately for each question (non-blocking for caller).
        """
        if self.has_active_session():
            return await self._handle_answer(user_text, speak_fn)
        else:
            return await self._start(user_text, speak_fn)

    def abandon(self):
        if self._active_id:
            s = self._sessions.get(self._active_id)
            if s:
                s.completed = True
        self._active_id = None

    # ── SESSION FLOW ───────────────────────────────────────────────────────

    async def _start(self, query: str, speak_fn: Callable) -> Optional[str]:
        sid = str(uuid.uuid4())[:8]
        category = self._detect_category(query)
        constraints = self._extract_constraints(query)

        session = RecommendationSession(
            session_id=sid,
            original_query=query,
            category=category,
            known_constraints=constraints,
            answers={},
            questions_asked=[]
        )
        self._sessions[sid] = session
        self._active_id = sid

        logger.info(f"🎯 Advisor [{sid}] {category} | known={constraints}")

        q = await self._next_question(session)
        if q:
            speak_fn(q)
            session.questions_asked.append(q)
            return None
        # Edge case: no questions needed (highly specific query)
        return await self._research_and_recommend(session, speak_fn)

    async def _handle_answer(self, answer: str, speak_fn: Callable) -> Optional[str]:
        session = self._sessions.get(self._active_id)
        if not session:
            return None

        last_q = session.questions_asked[-1] if session.questions_asked else "general"
        session.answers[last_q] = answer
        logger.info(f"   Answer: '{answer}'")

        # After 3 questions OR enough info, go to research
        if len(session.questions_asked) >= 3 or await self._enough_info(session):
            speak_fn("Got it. Researching the best options for you now.")
            return await self._research_and_recommend(session, speak_fn)

        q = await self._next_question(session)
        if q:
            speak_fn(q)
            session.questions_asked.append(q)
            return None

        speak_fn("Thanks. Looking up the best options now.")
        return await self._research_and_recommend(session, speak_fn)

    # ── QUESTION GENERATION ────────────────────────────────────────────────

    async def _next_question(self, session: RecommendationSession) -> Optional[str]:
        pool = self.QUESTION_POOL.get(session.category, self.QUESTION_POOL["_default"])
        known_text = " ".join(str(v) for v in {
            **session.known_constraints,
            **session.answers
        }.values()).lower()

        available = []
        for q in pool:
            if q in session.questions_asked:
                continue
            # Skip budget questions if budget already known
            if any(w in q.lower() for w in ["budget", "price", "cost", "much"]):
                if any(w in known_text for w in ["₹", "rs", "k", "under", "000"]):
                    continue
            # Skip brand if already known
            if "brand" in q.lower() and any(b in known_text for b in [
                "samsung", "apple", "oneplus", "realme", "poco", "xiaomi", "mi",
                "redmi", "vivo", "oppo", "motorola", "nokia", "sony", "dell",
                "hp", "lenovo", "asus", "acer", "lg", "bose", "jbl", "boat"
            ]):
                continue
            available.append(q)

        if not available:
            return None
        if len(available) == 1:
            return available[0]

        # LLM picks the most useful next question
        try:
            known_summary = {**session.known_constraints, **session.answers}
            prompt = (
                f"User wants a {session.category} recommendation.\n"
                f'Original query: "{session.original_query}"\n'
                f"What we already know: {json.dumps(known_summary)}\n"
                f"Questions already asked: {session.questions_asked}\n\n"
                f"Pick the SINGLE most useful follow-up question from:\n"
                f"{json.dumps(available)}\n\n"
                f"Return ONLY the question text, nothing else."
            )
            resp = await self._llm_call(prompt, max_tokens=60, temp=0.2)
            q = resp.strip().strip('"\'')
            if len(q) > 10 and ("?" in q or len(q) > 20):
                return q
        except Exception as e:
            logger.warning(f"Question LLM failed: {e}")

        return available[0]

    async def _enough_info(self, session: RecommendationSession) -> bool:
        known = {**session.known_constraints, **session.answers}
        all_text = " ".join(str(v) for v in known.values()).lower()
        has_budget = any(c in all_text for c in ["₹", "rs", " k", "under", "000", "lakh"])
        has_use = len(session.answers) >= 1
        return has_budget and has_use

    # ── RESEARCH + RECOMMENDATIONS ─────────────────────────────────────────

    async def _research_and_recommend(
        self, session: RecommendationSession, speak_fn: Callable
    ) -> str:
        known = {**session.known_constraints, **session.answers}
        query = self._build_search_query(session, known)
        logger.info(f"🔍 Researching: {query}")

        research = await self._web_search(query)
        result = await self._format_recommendations(session, known, research)

        session.completed = True
        session.result_text = result
        self._active_id = None
        return result

    def _build_search_query(self, session: RecommendationSession, known: Dict) -> str:
        parts = [f"best {session.category}"]
        budget = known.get("budget", "")
        if budget:
            parts.append(budget)
        for k, v in known.items():
            if k != "budget" and v and isinstance(v, str) and len(v) < 80:
                parts.append(v)
        parts.append("India 2025 review buy price")
        return " ".join(parts)

    async def _web_search(self, query: str) -> str:
        try:
            from duckduckgo_search import DDGS
            with DDGS(timeout=12) as ddgs:
                results = list(ddgs.text(query, max_results=6))
            formatted = []
            for r in results:
                formatted.append(
                    f"[{r.get('title','')}]\n{r.get('body','')[:400]}\nURL: {r.get('href','')}"
                )
            return "\n\n".join(formatted)
        except Exception as e:
            logger.warning(f"DDG search failed: {e}")
            return f"Search unavailable ({e}). Answering from training knowledge."

    async def _format_recommendations(
        self, session: RecommendationSession, known: Dict, research: str
    ) -> str:
        known_str = "; ".join(f"{k}: {v}" for k, v in known.items() if v)
        prompt = f"""You are Jarvis, a precise product advisor for Indian users.

User wants: {session.original_query}
Their preferences: {known_str}

Research data:
{research[:3500]}

TASK: Recommend exactly 3 {session.category}s that best match their needs.

FORMAT (follow exactly):
**Option 1: [Full Product Name]**
Specs: [3-4 key specs]
Why this suits you: [1 sentence tailored to their stated needs]
Price: ₹[amount]
Buy on Flipkart: https://www.flipkart.com/search?q=[url-encoded-product-name]
Buy on Amazon: https://www.amazon.in/s?k=[url-encoded-product-name]

**Option 2: [Full Product Name]**
[same format]

**Option 3: [Full Product Name]**
[same format]

**My Top Pick: [Name]**
[One sentence: why this is the best fit for THIS user's specific needs]

Rules:
- Use REAL product names that exist in India
- Build Flipkart/Amazon search URLs using the product name (URL-encode spaces as +)
- Prices must be realistic for India in 2025
- Tailor each "Why this suits you" to what the user actually said they need"""

        try:
            result = await self._llm_call(prompt, max_tokens=900, temp=0.35,
                                          system="You are Jarvis, a precise product advisor. Give specific, accurate recommendations for the Indian market.")
            return result.strip()
        except Exception as e:
            logger.error(f"Recommendation LLM failed: {e}")
            return f"Research complete, but I had trouble formatting the results. Try asking again."

    async def _llm_call(self, prompt: str, max_tokens=200, temp=0.3, system="") -> str:
        loop = asyncio.get_event_loop()
        client = self._groq()
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        def _call():
            return client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=messages,
                temperature=temp,
                max_tokens=max_tokens
            )
        resp = await loop.run_in_executor(None, _call)
        return resp.choices[0].message.content

    # ── HELPERS ────────────────────────────────────────────────────────────

    def _detect_category(self, text: str) -> str:
        t = text.lower()
        for cat, kws in self.CATEGORY_MAP.items():
            if any(kw in t for kw in kws):
                return cat
        return "product"

    def _extract_constraints(self, text: str) -> Dict:
        constraints = {}
        t = text.lower()

        # Budget: "under 20000", "20k", "₹15000", "below 30k", etc.
        budget_re = [
            r'(?:under|below|within|upto|up to|less than)\s*(?:₹|rs\.?|inr)?\s*(\d[\d,]*)\s*(?:k)?',
            r'(?:₹|rs\.?|inr)\s*(\d[\d,]*)\s*(?:k)?',
            r'\b(\d+)\s*k\b',
            r'\b(\d[\d,]+)\s*(?:rupees?|inr)\b',
        ]
        for pat in budget_re:
            m = re.search(pat, t)
            if m:
                raw = m.group(1).replace(",", "")
                num = int(raw)
                if num < 1000:
                    num *= 1000
                constraints["budget"] = f"under ₹{num:,}"
                break

        # Brand hints
        brands = [
            "samsung", "apple", "oneplus", "realme", "poco", "motorola",
            "nokia", "xiaomi", "mi", "redmi", "vivo", "oppo", "asus",
            "dell", "hp", "lenovo", "acer", "msi", "sony", "bose", "jbl",
            "boat", "sennheiser", "lg", "google", "nothing"
        ]
        found = [b for b in brands if b in t]
        if found:
            constraints["brand_preference"] = ", ".join(found)

        return constraints

    @staticmethod
    def spoken_summary(full_text: str) -> str:
        """Convert full recommendation report to a concise spoken version."""
        lines = full_text.split("\n")
        parts = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("**Option"):
                # "**Option 1: Samsung Galaxy A35**" → "Option 1: Samsung Galaxy A35"
                parts.append(line.replace("**", ""))
            elif "My Top Pick" in line:
                parts.append(line.replace("**", ""))
            elif line.startswith("Why this suits you:"):
                parts.append(line)
            elif line.startswith("Price:"):
                parts.append(line)
        # Keep it under ~20 seconds of speech
        summary = " | ".join(parts[:10])
        if not summary:
            # Fallback: strip markdown
            clean = re.sub(r'\*{1,2}([^*]+)\*{1,2}', r'\1', full_text)
            clean = re.sub(r'https?://\S+', '', clean)
            summary = clean[:400].strip()
        return summary
